In [2]:
from __future__ import absolute_import

import random

import matplotlib.pyplot as plt
import numpy as np
import scipy.io
import scipy.misc
from scipy.spatial import distance

import cv2


def get_centroids_2(samples, clusters):
    num_of_clusters = 2
    
    
    #Initialize the centroid array
    final_centroids = []
    centroid_2D = [0 for j in range(num_of_clusters)]
    num_of_samples = len(samples)
    centroid_2D_point_count = [0 for i in range(num_of_clusters)]
    
    
    
     
    #iterating through each samples
    for i in range(num_of_samples):
        
        #counting the number of elements in each cluster
        sample_cluster = clusters[i]
        centroid_2D_point_count[sample_cluster] += 1
        
        #add up all the individual cluster x1 and x2 elements
        centroid_2D[sample_cluster] += samples[i]
        
        
    
        
    #calculate the final mean
    for i in range(num_of_clusters):
        centroid_pair = []
        centroid_2D[i] = centroid_2D[i] / centroid_2D_point_count[i]
        centroid_pair.append(centroid_2D[i])
        final_centroids.append(centroid_pair)
    
    
    
    
    
    
    
    
    return final_centroids
    """
    Find the centroid given the samples and their cluster.
    :param samples: samples.
    :param clusters: list of clusters corresponding to each sample.
    :return: an array of centroids.
    """
    pass




def find_closest_centroids_2(samples, centroids):
    
    
    clusters = []
    
    #Iterate through every sample
    for i in range(len(samples)):
        distance = []
        
        
        ##print(type(centroids))
        
        #iterate through every cluster for every sample
        for j in range(len(centroids)):


            #store the eucledian distance in a array
            distance.append(samples[i]-centroids[j]);

        
        index = distance.index(min(distance)) 
        clusters.append(index);
    
    
    return clusters;
    """
    Find the closest centroid for all samples.
    :param samples: samples.
    :param centroids: an array of centroids.
    :return: a list of cluster_id assignment.
    """
    pass


def run_k_means_2(samples, initial_centroids, n_iter):
    """
    Run K-means algorithm. The number of clusters 'K' is defined by the size of initial_centroids
    :param samples: samples.
    :param initial_centroids: a list of initial centroids.
    :param n_iter: number of iterations.
    :return: a pair of cluster assignment and history of centroids.
    """

    
    current_centroids = np.array(initial_centroids)
    clusters = []
    for iteration in range(n_iter):
        clusters = find_closest_centroids_2(samples, current_centroids)
        current_centroids = np.array(get_centroids_2(samples, clusters))

    return clusters, current_centroids


def choose_random_centroids_2(samples, K):
    random_centroids = []
    np.random.permutation(samples)
    for i in range(K):
        random_centroid_point = []
        random_centroid_point.append(samples[i])
        random_centroids.append(random_centroid_point)
        
        
    return random_centroids
        
        
    
    """
    Randomly choose K centroids from samples.
    :param samples: samples.
    :param K: K as in K-means. Number of clusters.
    :return: an array of centroids.
    """
    pass

def kmeans2(sample):
    print("good kmeans")


    

    initial_centroids = choose_random_centroids_2(sample , 2)
    #Initial clstering with the initial centroids
    clusters = np.array(find_closest_centroids_2(sample, initial_centroids))
  
    #The clusters after Running K meams
    clusters , centroid_values = run_k_means_2(sample, initial_centroids, n_iter=10)
    
    
   

if __name__ == '__main__':
    print("In Main")
    img = cv2.imread('boston.jpg')
    print(type(img))
    print(img)

    centre_values = []
    clusters , centre_values = kmeans2(img)




In Main
<class 'numpy.ndarray'>
[[[212 167 129]
  [213 168 130]
  [213 169 128]
  ...
  [165 146 103]
  [169 150 107]
  [147 128  85]]

 [[211 166 128]
  [212 167 129]
  [212 168 127]
  ...
  [166 147 104]
  [170 151 108]
  [148 129  86]]

 [[210 165 127]
  [212 167 129]
  [212 168 127]
  ...
  [166 147 104]
  [171 152 109]
  [150 131  88]]

 ...

 [[ 99 154 129]
  [ 83 138 113]
  [102 157 132]
  ...
  [218 245 249]
  [218 249 250]
  [196 230 229]]

 [[ 81 138 113]
  [ 82 139 114]
  [ 71 128 103]
  ...
  [209 238 242]
  [213 245 244]
  [192 225 221]]

 [[ 73 130 105]
  [ 84 141 116]
  [ 73 130 105]
  ...
  [204 235 238]
  [193 226 222]
  [156 190 184]]]
good kmeans


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()